spring:
  rabbitmq:
    host: 103.218.240.252
    port: 5672 # 端口
    virtual-host: /t-music # 虚拟主机
    username: tmusic # 用户名
    password: tmusic # 密码
    connection-timeout: 10000  # 单位是毫秒
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    password: olbc ebfe xdsh tvid
    username: t84323700@gmail.com
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            #            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 25
          starttls:
            enable: true
            required: true
  ai:
    openai:
      api-key: sk-a5ede5cfd4b649dd950b75e315fbac51
      base-url: https://api.deepseek.com
      model: deepseek-chat
  servlet:
    multipart:
      # 设置传输大小
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://103.218.240.252:3306/tnotes
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://t-music:t-music@103.218.240.252:27017/music_lyrics_db
  # redis配置
  redis:
    # 地址
    host: 103.218.240.252
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password: 1234
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mybatis:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰
    map-underscore-to-camel-case: true
  # mapper.xml 文件夹所在位置
  mapper-locations: classpath:mapper/**/*.xml


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true
minio:
  # minio地址
  endpoint: http://103.218.240.252:9000
  # 账户
  username: admin
  # 密码
  password: admin@pwd
  #存储桶
  defaultBucketName: tmusic-oss